sudo: required
language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

install:
  - sudo apt-add-repository ppa:git-core/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install git -y
  - make deps
